galaxy_info:
  author: Tom Bosmans
  description: Retrieve entry info from Pleasant password server
  company: IBM
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
   - name: GenericLinux
     versions:
     - all
  galaxy_tags: []
dependencies: []
